### ISSUE TITLE
How to implement the Latent Code Arithmetic?

### ISSUE THREAD

**Issue by liang3588** [edward1997104/Neural-Template#3]
Great work!
I wonder that how to implement the Latent Code Arithmetic, including the shape arithmetic and topological arithmetric.

**Comment by edward1997104** [comment]
We separate the encoded latent vector into 2 parts, the first 128 dimensions are the shape code and the last 128 dimensions are the topology code. You can perform the arithmetic in only one of the spaces by changing the first 128 dimensions or the last 128 dimensions.
