### ISSUE TITLE
Training in discrete phase

### ISSUE THREAD

**Issue by elmiraloo** [edward1997104/Neural-Template#4]
Thanks for the paper/code. In the paper you mentioned the discrete phase of training has only been done on 64^3 voxels. But in `configs_discrete.py` you shared,  the starting phase is 0. Is this file the same as the one you used for the paper?

**Comment by edward1997104** [comment]
Thank you for your interest! The config is mostly the same as the one we used in the paper and we only use 64^3 for training the discrete phrase. The starting phase is a typo during the refactoring of the codes and it is now fixed. Thank you for the reminder!

**Comment by elmiraloo** [comment]
Thanks for the quick response.
