### ISSUE TITLE
loss range

### ISSUE THREAD

**Issue by elmiraloo** [edward1997104/Neural-Template#6]
I'm trying to debug the pipeline for a different setting. I was wondering if you have the loss range for beginning and end of each phase (approximately) or the overall loss range

**Comment by edward1997104** [comment]
For the continuous phase, the loss after 3 phases are around 0.0003, 0.0037 and 0.012 respectively. The loss after the discrete phase is around 0.015.

**Comment by elmiraloo** [comment]
thank you
