### ISSUE TITLE
"no module named models"

### ISSUE THREAD

**Issue by 19dx** [edward1997104/Neural-Template#7]
Thanks for your amazing work!
When I try to run the test command, I encounter this error: "no module named models". 
<img width="360" alt="c7ef5d8daca9b7e8f1e380f68bece27" src="https://user-images.githubusercontent.com/95059944/201476772-baa56586-3830-4111-937c-4e0a5c67aca6.png">

I don't know how to fix it.

**Comment by edward1997104** [comment]
It is highly possible that you have not added the project root to PYTHONPATH environment variable. Hope this would be helpful!

**Comment by 19dx** [comment]
> It is highly possible that you have not added the project root to PYTHONPATH environment variable. Hope this would be helpful!

You are right, thanks!!!
