### ISSUE TITLE
Terminate in debugger.py

### ISSUE THREAD

**Issue by farhadi76m** [edward1997104/Neural-Template#8]
Hi , I had been trying to run your code in Google Colab , but after I ran , without any errors kernel had stopped! 
I tried to find where this problem was happened and in  debugger.py in this part:
```
        ######## redirect the standard output
        if is_save_print_to_file:
            sys.stdout = open(self.file_path("print.log"), 'w')

            ######## print the dir again on the log
            print("=================== Program Start ====================")
            print(f"Output directory: {self._debug_dir_name}")
```
kernel interrupted ! 
Could You Help ME ?! 
Thank you

**Comment by edward1997104** [comment]
We try to redirect all standard inputs to a file here that might cause the problem. You might set the flag (is_save_print_to_file) in the trainer as False to see if this helps.

**Comment by farhadi76m** [comment]
Thank You It worked perfectly =)
